### ISSUE TITLE
Edge missing in: Sharma, Venkatesh Narayan

### ISSUE THREAD

**Issue by MyriamSchmidt** [swiss-art-research-net/itten-app#103]
Sharma, Venkatesh Narayan is recipient of "Korrespondenz zwischen Venkatesh Narayan Sharma und Johannes Itten" which is visible in the Infoblatt, but the corresponding edge "empfing" is missing in the graph.
Or is this due to the double role concering the same document?

**Comment by fkraeutli** [comment]
Yes, unfortunately double edges are not yet supported by SigmaJS
