### ISSUE TITLE
Edge labelling still incorrect in some unidentified persons

### ISSUE THREAD

**Issue by MyriamSchmidt** [swiss-art-research-net/itten-app#106]
The graph from the entities "Zahlreiche Kollegen" and "Viele Kollegen" doesn't map the given AAT-thesaurus relations (Bildungseinrichtung, Lehrer), instead only show "steht in Bezug zu". 
In the infotext from the pattern for unidentified persons, the AAT-terms (educational institution and teacher) are visible, which should not be the case.

**Comment by MyriamSchmidt** [comment]
Update: These errors still persist after the latest upload.

**Comment by fkraeutli** [comment]
remark:
```
Entität: Zahlreiche Kollegen Typ: Person Rolle: Erwähnt (Empty) Bemerkungen: Der Leiter des Hessischen Lehrerfortbildungswerkes, Hauptstelle Reinhardswaldschule #GND2011847-8 (educational institution #AAT300386368) Dr. Arthur Faulwasser #GND105528527X freut sich über Ittens #GND118710990 (teacher #AAT300025529) Zusage, den von zahlreichen Kollegen gewünschten Fortsetzungslehrgang zur Farblehre 1957 durchzuführen (Quelle: Hs NL 11: Fc 3) Anzahl: >1
```

**Comment by fkraeutli** [comment]
Die Beziehungen müssten explizit als Beziehungen angegeben werden. Sie stehen momentan nur in den Benerkungen.

z.B.
Entität: Zahlreiche Kollegen Typ: Person Rolle: Erwähnt (Empty) Bemerkungen: Der Leiter des Hessischen Lehrerfortbildungswerkes, Hauptstelle Reinhardswaldschule #GND2011847-8 ~~(educational institution #AAT300386368)~~ Dr. Arthur Faulwasser #GND105528527X freut sich über Ittens #GND118710990 (teacher #AAT300025529) Zusage, den von zahlreichen Kollegen gewünschten Fortsetzungslehrgang zur Farblehre 1957 durchzuführen (Quelle: Hs NL 11: Fc 3) Anzahl: >1 **Beziehungen: Hessisches Lehrerfortbildungswerkes, Hauptstelle Reinhardswaldschule #GND2011847-8 (educational institution #AAT300386368)**

**Comment by MyriamSchmidt** [comment]
Mist, jetzt sehe ich es auch.
Fehler aus den Quelldaten können wir zum jetzigen Zeitpunkt nicht mehr beheben, richtig?

**Comment by fkraeutli** [comment]
Closing this as data update discussions moved to different channel
