### ISSUE TITLE
Missing relation/edge

### ISSUE THREAD

**Issue by JoelleFischer** [swiss-art-research-net/itten-app#108]
Walden, Herwarth and Nell Walden are a married couple according to GND but in JILA isn't showing this relation in graph and info.

**Comment by fkraeutli** [comment]
Seems like RDF only lists them as a `gndo:familialRelationship` but does not include information displayed in front-end:
<img width="428" alt="Screenshot 2023-09-19 at 11 39 27" src="https://github.com/swiss-art-research-net/itten-app/assets/1564625/a3e46d40-dd9b-4e12-bcbb-633b05278cc0">
need to check if this information is present somewhere else in the RDF

**Comment by fkraeutli** [comment]
It would need to be in the GND
