### ISSUE TITLE
All right-clicks lead to the focused entity 

### ISSUE THREAD

**Issue by MyriamSchmidt** [swiss-art-research-net/itten-app#109]
i.e. Johannes Itten:
Every link in the info (be it a document, person or group or the "Link zur Quelle") that I want to open in a new tab via right click leads back to Johannes Ittens persona site. From a philosophical point of view it's not wrong but technically it doesn't seem to be right ;-)

**Comment by fkraeutli** [comment]
great observation! will investigate
