### ISSUE TITLE
Incorrect sorting on starting page - persons

### ISSUE THREAD

**Issue by MyriamSchmidt** [swiss-art-research-net/itten-app#122]
On the persons starting page, the first name to appear is "54 Teilnehmer am IV. Kurs an der Rheinhardwaldschule Kassel".

![Startseite_A](https://github.com/swiss-art-research-net/itten-app/assets/127132969/b846b24d-33cf-40fd-9200-60175cb1ccfc)

Accordingly, names with a special character as initial appear at the end of the list:

![Sonderzeichen](https://github.com/swiss-art-research-net/itten-app/assets/127132969/1751e48d-f6df-4035-a768-7e526a4e7349)

**Comment by fkraeutli** [comment]
Yes, since in the alphabetic order returned by the triple store, numbers come before letters. I'll check if there is a way to influence this
