### ISSUE TITLE
Fix filter "identified" (!)

### ISSUE THREAD

**Issue by MyriamSchmidt** [swiss-art-research-net/itten-app#124]
Filter "identified - false" counts 116 persons.

I count 213 (!) unidentified entities.

This would be very important to fix!

**Comment by fkraeutli** [comment]
Do you have an example of an unidentified person that should appear, but does not?

Is the number of identified persons correct?

**Comment by MyriamSchmidt** [comment]
It seems that using the filter for unidentified persons, I can find all the names I'm looking for.

So it's just the number of unidentified persons in the filter that is not correct. 

Not sure if we can find out the correct number of identified persons in the Quelldaten...

**Comment by fkraeutli** [comment]
Hm not sure I understand. How do you arrive at 213?

**Comment by MyriamSchmidt** [comment]
I counted all the entities with type "person" in the Quelldaten (manually). If they appear multiple times I only counted them once. I also found 1incorrect data scheme, but still there should be over 200 unidentified persons at least...

**Comment by fkraeutli** [comment]
I have checked in the remarks and I can only find 116 unique(!) persons. There are some that appear several times:
```python
{'54 Teilnehmer am IV. Kurs an der Rheinhardswaldschule Kassel': 1,
 'Abegg': 1,
 'Alter Bekannter von Johannes Itten': 1,
 'An Johannes Ittens Kunst der Farbe interessierte Person': 1,
 'Angestellter der Musei Vaticani': 1,
 'Architekt an der Documenta III': 1,
 'Architekt in Pretoria': 1,
 'Bauer in Flirsch, Gastgeber von Johannes Itten': 1,
 'Bauhausdirektion 1919': 1,
 'Bayerischer Meister Ende 14. Jh.': 1,
 'Bedienerin Johannes Ittens': 1,
 'Bert': 1,
 'Berühmter Kunstgelehrter': 2,
 'Bildhauer': 1,
 'Bl.': 1,
 'Braun 1': 1,
 'Braun 2': 1,
 'Bull.': 1,
 'Böhmischer Meister 14. Jh.': 1,
 'Chr. v. A.': 1,
 'Chung Ssü-Kung': 1,
 'Costantini': 1,
 'Dame': 1,
 'Direktor der Chirurgischen Klinik Zürich im Jahr 1961': 1,
 'Dr. Grünwald': 1,
 'Dr. Hartmann': 1,
 'Dr. Kronenberger': 1,
 'Dr. Melcher': 1,
 'Dr. Zellweger': 1,
 'Ehemann der Ziehschwester von Anna Höllering': 1,
 'Feuerstack': 1,
 'Francesko': 1,
 'Frau Wegener': 1,
 'Frau eines berühmten Kunstgelehrten': 2,
 'Frau von Fournier': 1,
 'Frl. Dahl': 1,
 'Fuhrknecht in Salzburg': 1,
 'Fürst Schwarzenberg': 1,
 'Gasmann': 1,
 'Gipsgiesser, der Johannes Ittens Modell bearbeitet': 1,
 'Graber': 1,
 'Gunhild': 1,
 'Gör.': 1,
 'H. Bg.': 1,
 'Hagemann': 1,
 'Hermann': 1,
 'Hintermann': 1,
 'Inspektor einer Primarschule': 2,
 'Junger Sonnengott im Triumphwagen': 1,
 'Kaiser der Handynastie': 2,
 'Klaus': 1,
 'Konkurrent von Lucia Moholy bei der Berufung auf eine Professur': 1,
 'Kritiker an der Documenta III': 1,
 'Kunstsammler Goloubeff': 1,
 'Kunstschüler Ittens': 1,
 'Köppler': 1,
 'Lange': 1,
 'Lenerl': 1,
 'Li Chien': 1,
 'Lor.': 1,
 'Mann der schönen Bürgerin': 1,
 'Maria': 1,
 'Matthieu': 1,
 'Maurermeister um 1919 in Weimar': 1,
 'Miss Parker': 1,
 'Misserl': 1,
 'Natascha': 1,
 'Natascha D.': 1,
 'Nießen': 1,
 'Nä.': 1,
 'Oskar Schlemmers Bruder in Kaupen': 1,
 'Oskar Schlemmers Schwiegermutter': 1,
 'Palmgreen': 1,
 'Pestalozzi': 1,
 'Plumperl': 1,
 'Portier des Österreichischen Museums für Kunst und Industrie': 1,
 'Prof. Patzek': 1,
 'Rasch': 1,
 'Rauh': 1,
 'Referent für Kunsterziehung an den staatlichen Schulen': 1,
 'Resi': 1,
 'Ru.': 1,
 'Rub.': 1,
 'Russischer Künstler oder Kunstpädagoge': 1,
 'Sabine P.': 1,
 'Scheper': 1,
 'Schifer': 1,
 'Schmitt': 1,
 'Schoch': 1,
 'Schottische Grossmutter': 1,
 'Schulrat Engel': 1,
 'Schwedischer Industrieller': 1,
 'Schwägerin von Resi': 1,
 'Schöne Bürgerin': 1,
 'Schülerin Ittens an der Itten-Schule Berlin': 1,
 'Sekretär oder Sekretärin von Renato Bartoccini': 1,
 "Sekretär von Guglielmo De Angelis d'Ossat": 1,
 'Slowakischer Augenoperateur': 1,
 'Sohn von Helge Lindberg': 1,
 'Spie.': 1,
 'Stör.': 1,
 'Suzanne B.': 1,
 'Südfranzösische Grossmutter': 1,
 'Tochter von Adolf Hölzel': 4,
 'Tochter von Johannes Itten und Hildegard Anbelang': 1,
 'Tul.': 1,
 'Unterzeichner einer Erlaubnisurkunde des Provinzial-Schulkollegiums Berlin': 1,
 'Vater von Hildegard und Emmy Anbelang': 1,
 'Von Johannes Itten am 26.05.1918 zu empfangender Besuch': 1,
 'Weberin': 1,
 'Wind.': 1,
 'Wärter der Musei Vaticani': 1,
 'Yogi': 1,
 'Yoshioka': 1,
 'Ziehschwester von Anna Höllering': 1,
 'v. Falk.': 1}
```

**Comment by MyriamSchmidt** [comment]
The following are missing in the above list (though I can find their names by searching in the filter "identified - false"

Teilnehmer am Lehrkurs 1954 
Zurückgewiesene Teilnehmer
Neue Teilnehmer am Lehrkurs 1955
Alle Teilnehmer am Lehrkurs 1955 
Viele Kollegen
Neue Teilnehmer am Farbkurs 1956
Zahlreiche Kollegen
40 Teilnehmer
40 Kunsterzieher aus Bayern 
Gäste eines schwedischen Industriellen 
Mongolischer Grosselternteil von Natascha 
Mongolische Vorfahren von Natascha D. 
Jesuiten an der Kaulbachstrasse in München
Russische Vorfahren von Natascha D. 
Griechische Vorfahren von Natascha D. 
Monteur am Velum im Stedelijk Museum Amsterdam 1938
Monteure am Velum im Stedelijk Museum Amsterdam 1938 
Freunde von Lucia Moholy in London
Die Menschen von Flirsch 
Schüler von Johannes Itten im Atelier an der Nussdorferstrasse in Wien 
Potenzielle Schüler Ittens 1919
Menschen am Bauhaus 1919 
100-150 Zuhörer
Kollegen Johannes Ittens an der Textilfachschule Zürich
Lehrkörper an der Textilfachschule Zürich 
Acht Herren 
Versammlung von Textilindustriellen 
Versammlung von Textilindustriellen im Jahr 1937 
Freunde von Johannes Itten in Amsterdam
Freunde von Johannes Itten in Amsterdam
Schüler und Schülerinnen der Textilfachschule Krefeld
Kollegen Ittens an der Textilfachschule Krefeld 
Ausstellungsleitung der Berliner Reichstextilausstellung 1937 
Künstler in Stellungnahme zu einer schweizerischen Kunstakademie 
Kandidaten für die Direktorenstelle des Kunstgewerbemuseums Zürich 1938
Mitglieder des Internationalen Museumsrats 1948
Teilnehmer der Biennale des ICOM 1948 in Paris 
Mitglieder des Stadtrates von Zürich 1948 
Schüler Ittens, die 1944 an der Ausstellung "Die Farbe" in Zürich mitarbeiten 
Schüler Ittens, deren Arbeiten mit einem Teil der Ausstellung "Die Farbe" in mehreren Städten Deutschlands gezeigt werden 
Schülerinnen und Schüler der Itten-Schule Berlin
Schüler der Itten-Schule Berlin 
Schüler der Itten-Schule Berlin 1931
Lehrerschaft des Progymnasiums Thun im Jahr 1904 
Schwarzenburger Schulklasse 
Vollschüler von Johannes Itten 
Schüler von Johannes Itten 
Hospitanten bei Johannes Itten 
Abendschüler von Johannes Itten 
Neuaufnahmen im Unterricht von Johannes Itten 
Mitarbeiter Johannes Ittens an der Höheren Fachschule für Textile Flächenkunst 
Kinder der schönen Bürgerin
Menschen vor dem Eingang der Musei Vaticani am 4. November 1950 
Besucherstrom in den Musei Vaticani am 4. November 1950 
Mitglieder des Consiglio superiore per le antichità e belle arti am 6. November 1950 
Gesandtschaft Indien
Gesandtschaft China
Gesandtschaft Japan
Hubers in Zürich 
Basler Museumsleute um ca. 1937-1938 
Publikum des Vortrages "Allgemeine Erziehung und Kunsterziehung" 
Vorstand der Schweizerischen Gesellschaft für ostasiatische Kultur
Aufsichtssektion und -kommission des Kunstgewerbemuseums Zürich
Leitung des Kunstgewerbemuseums Zürich 
Vorstand des Schulamts der Stadt Zürich 
Leihgeber der Ausstellung Asiatische Kunst aus Schweizer Sammlungen 
Mitarbeiter der Ausstellung Asiatische Kunst aus Schweizer Sammlungen 
Besucher der Ausstellung Asiatische Kunst aus Schweizer Sammlungen 1941 in Zürich 
Rinascente-Leute 
Kunsterzieher der städtischen und staatlichen höheren Schulen in Bayern 
An einem Farbkurs interessierte Lehrer der Fachhochschulen Bayern
Schüler von Johannes Itten am Staatlichen Bauhaus Weimar 
Einige Schüler von Johannes Itten am Staatlichen Bauhaus Weimar 
Schüler von Johannes Itten in Wien und am Staatlichen Bauhaus Weimar
Schüler von Johannes Itten in Wien 
Meisterrat 
Stiftermönche
Stifterfiguren
Gratulanten zu Walter Gropius' 70. Geburtstag 
Amerikanische Freunde von Conrad Herrmann um 1938
Massgebliche Herren des Dupont-Konzerns um 1938 
Direktoren der amerikanischen Glanzstoffwerke 
Amerikanische Fabrikanten, von Walter Gropius um 1938 kontaktiert 
Freunde von Walter Gropius in Amerika 
Um 1953 noch lebende Bauhäusler und Frauen von verstorbenen Bauhäuslern
Namhafte und nicht unreiche Bauhäusler 
Schüler von Richard Engelmann 
Schüler von Walther Klemm 
Schüler von Max Thedy 
Schüler von Lyonel Feininger 
Schüler von Gerhard Marcks 
Architekten in Korrespondenz mit der Zeitschrift Frühlicht um 1920 
Freunde von Bruno Taut
Schüler des Bauhauses Weimar 
Ehemalige Schüler von Leopold von Kalckreuth 
Assistenten von Johannes Itten an der Itten-Schule Berlin
Primarschüler von Johannes Itten auf Stufe des 6. und 7. Schuljahres

**Comment by fkraeutli** [comment]
I have checked a few and they might have been resolved with #117. For some reason, groups were no longer displayed
