### ISSUE TITLE
Barocelli, Pietro: Wrong Dates of Birth and Death

### ISSUE THREAD

**Issue by JoelleFischer** [swiss-art-research-net/itten-app#125]
Dates of Birth and Death from "Barocelli, Pietro" are incorrectly displayed on JILA.
On GND it is "1887 - 1981". On JILA we have "1887 - 22.12.1887" with reference to GND.
(http://10.51.1.212/resource/actor:BD9AD14A-1A12-333E-A29F-86E2D93C29E3)

**Comment by fkraeutli** [comment]
The information comes from CMI and needs to get fixed there:
```json

        {
            "Register Bezeichnung": "Barocelli, Pietro",
            "Register GND-ID": "1018674667",
            "Register Rolle": "Erwähnt (Empty)",
            "Register Datum": "1887 - 1981",
            "Register ID": "67586",
            "Registertyp": "Personenregister",
            "Register Bemerkungen": "Link zur GND: <a href=http://d-nb.info/gnd/1018674667 target=\"_blank\">GND</a>"
        }
```

**Comment by fkraeutli** [comment]
Ah no sorry! That is the correct information

**Comment by fkraeutli** [comment]
The information comes from Lobid, which is where we get the Linked Data information from GND: https://lobid.org/gnd/1018674667

I check if we can report the error

**Comment by fkraeutli** [comment]
According to Lobid the information is incorrect in the RDF delivered from GND

> danke für die Meldung. Das ist bereits im von der DNB gelieferten [RDF]
nicht korrekt, das als Basis für lobid dient.

> Wenn ich mir das [MARC21] anschaue, dann sehe ich da auch den Fehler und
zwar in Feld 548:


 ```xml
<datafield tag="548" ind1=" " ind2=" ">
  <subfield code="a">-22.12.1887</subfield>
  <subfield code="4">datx</subfield>
  <subfield
code="4">https://d-nb.info/standards/elementset/gnd#dateOfDeath</subfield>
  <subfield code="w">r</subfield>
  <subfield code="i">Exakte Lebensdaten</subfield>
</datafield>```

Is this something you can fix at ZBZ or should I pass it back to them?

**Comment by JoelleFischer** [comment]
Thanks for the info. I have passed it on to our in-house GND Redaktion and asked if they could fix it. I'll write an update as soon as I get a feedback.

**Comment by JoelleFischer** [comment]
The GND Redaktion fixed the Dates of Birth and Death of Barocelli in RDF. But it seems Lobid hasn't jetzt adapted the new data.

**Comment by JoelleFischer** [comment]
I've just checked if the deathdate on lobid has been adapted but they are still falsely displayed even though the RDF has been updated. Is it sufficient for JILA if the RDF is correct to display the correct DateOfDeath?

**Comment by fkraeutli** [comment]
Needs to be re-retrieved. Currently running (cc #88)

**Comment by JoelleFischer** [comment]
Do you know how long the re-retrieval takes? Just that I know when to check for changes.

**Comment by MyriamSchmidt** [comment]
The dates are still incorrect. Can you do a re-retrieval?
