### ISSUE TITLE
Number of persons 

### ISSUE THREAD

**Issue by JoelleFischer** [swiss-art-research-net/itten-app#126]
Without a filter you get 1169 results in total. This doesn't match the combined results of "Identified" (true: 1039 and false: 116). There are some related issues I could identify:

1. There are 5 persons in the total results which are not visible in the results of the filter "Identified" (true or false):
- Bleek, Hanns
- Rauh, August
- Scheper, Hermann
- Scheper, Hinnerk
- Schlemmer, Carl
They have in common, that they are only listed as "possible matches". Other "possible matches" usually only appear when searched by name. They don't appear, when you scroll through the list. So the appearance of these five persons in the full results is an anomaly.

2. The total number of persons (without filter / 1169) is wrong. When counted the persons sum up to only 1161.

3. The total number of identified persons (filter "Identifiziert"-> "true"/ 1039) is also wrong. When counted there even are 1040 results displayed.

This problem could also have some overlap with #124.

**Comment by fkraeutli** [comment]
I'm not sure if I reproduce the reasoning correctly but there was a decision once taken that the list should only display persons that are defined in JILA. That means persons associated via a Register Entry or (unidentified) persons associated in the remarks. That's why the persons in 1 do not show up. 

When searching for them directly they do show up, which I think makes sense.

We can change that behaviour but it could lead to more persons to appear in the list that we don't want and I think that is what provoked the editorial decision to focus only on true JILA persons. I think another criterium was also that they are directly related to at least one document.

The other points could indeed be due to #124 and #117

**Comment by JoelleFischer** [comment]
Sorry I'll try to clarify what I meant with the latter two points: 

The filter _Identified_ - _false_  shows the 212 results it found.

When no filter is engaged "Found 1266 results" is displayed below the search bar. This does not tally with the numbers counted. There are 50 persons per page on 25 pages and there are seven persons on the last page. For me the "Found results" should amount to 1257.

Similar when I engage the filter _Identified_ as _true_: "Found 1039 results". We have 20 pages with each 50 persons on them and the last page (page 21) shows 40 persons. The persons it actually shows amount to 1040 not 1039.

**Comment by fkraeutli** [comment]
Ah now I understand! I will investigate

**Comment by fkraeutli** [comment]
There are 10 entities without labels

**Comment by fkraeutli** [comment]
Fixed various queries where numbers did not add up correctly

**Comment by JoelleFischer** [comment]
There still seems to be a problem: The found results without filter amount to 1266. When I count the persons displayed I find 1267.

Similar when I apply the filter "Identifiziert: true": The found results sum up to 1039 but I count 1040 displayed.

**Comment by fkraeutli** [comment]
1266 is correct. Seems that there is an extra one in the table. I'll investigate

**Comment by fkraeutli** [comment]
Kraus Karl appears twice when searching
<img width="454" alt="Screenshot 2023-12-19 at 15 15 18" src="https://github.com/swiss-art-research-net/itten-app/assets/1564625/411b9abd-4a03-433f-a5db-8cd632ad7c08">

**Comment by fkraeutli** [comment]
Karl Kraus appears to have the GND of Josef Mikl somewhere

<img width="609" alt="Screenshot 2023-12-19 at 15 18 27" src="https://github.com/swiss-art-research-net/itten-app/assets/1564625/9fbab80c-e195-4f33-b1b7-8b753d0a51c2">

**Comment by JoelleFischer** [comment]
Oh interesting. Kraus, Karl and Mikl, Josef had the same GND in CMI. I've just corrected Kraus, Karl's entry in our registry. Thanks for the hint.

**Comment by fkraeutli** [comment]
Yes I noticed too, seems to come from the source data:
```
,
        {
            "Register Bezeichnung": "Kraus, Karl",
            "Register GND-ID": "118582364",
            "Register Rolle": "Erwähnt (Empty)",
            "Register Datum": "1874 - 1936",
            "Register ID": "64572",
            "Registertyp": "Personenregister",
            "Register Bemerkungen": "Link zur GND: <a href=https://d-nb.info/gnd/118582364 target=\"_blank\">GND</a>"
        }
```

**Comment by fkraeutli** [comment]
What is Karl Kraus' GND?

**Comment by JoelleFischer** [comment]
118566288 ist Kraus' GND

**Comment by fkraeutli** [comment]
Ok. He only appears once so I see if I can change it manually in the source data

**Comment by fkraeutli** [comment]
Changed it and remapping the data now. Let's see how the person count looks afterwards

**Comment by fkraeutli** [comment]
Done

**Comment by JoelleFischer** [comment]
The numbers now seem to be correct. Thanks!
