### ISSUE TITLE
Filter "Beziehung zu Personen": 4 names gone missing

### ISSUE THREAD

**Issue by MyriamSchmidt** [swiss-art-research-net/itten-app#135]
Not sure when this happened?
![Unbenannt](https://github.com/swiss-art-research-net/itten-app/assets/127132969/276f8b8c-137a-4ccb-ba80-aaabf6cfdf8c)

**Comment by MyriamSchmidt** [comment]
The issue persists. Could you please take a look?

**Comment by fkraeutli** [comment]
Fixed
