### ISSUE TITLE
English translation frontend page "about JILA"

### ISSUE THREAD

**Issue by MyriamSchmidt** [swiss-art-research-net/itten-app#143]
This was already a topic and the textfile uploaded in #102:
When I started working on JILA there was already an english page implemented. Why can the german text not be replaced with an english version? Does this mean there is no technical possibilty at the moment to fill in an english version here, unlike the "persons" page?

**Comment by fkraeutli** [comment]
No, but we can add the English version underneath. Should we do this?

**Comment by fkraeutli** [comment]
Added English version with link

**Comment by MyriamSchmidt** [comment]
If I open the "English text below" - link in a new tab, I get to "Rechtliche Nutzungsbedingungen für Digitalisate". If I click on the link in the same tab the anchor is positioned correctly.

**Comment by thomashaensli** [comment]
Hi @MyriamSchmidt 
Florian is currently off. We will have a look at this asap (i.e. monday)
Very best Thomas

**Comment by fkraeutli** [comment]
Great observation! Should be fixed now
