### ISSUE TITLE
Entity (identifier) incorrect

### ISSUE THREAD

**Issue by MyriamSchmidt** [swiss-art-research-net/itten-app#144]
https://jila.zb.uzh.ch/resource/?uri=https://resource.jila.zb.uzh.ch/collection/jila-859afc5815a047a58569cee9db123f30

I can't find this identifier in our source data and it's unclear for me, what kind of data record this is.

**Comment by fkraeutli** [comment]
It's the parent record of the entire Itten collection in CMI. We can remove it, since there is no data about it in JILA

**Comment by fkraeutli** [comment]
See here: https://zbcollections.ch/home/#/content/859afc5815a047a58569cee9db123f30

**Comment by fkraeutli** [comment]
Removed
