### ISSUE TITLE
Incorrect colours in graph + info sheet

### ISSUE THREAD

**Issue by MyriamSchmidt** [swiss-art-research-net/itten-app#146]
The following group entities are pink instead of orange:

Mongolische Vorfahren von Natascha D.
Russische Vorfahren von Natascha D.  
Griechische Vorfahren von Natascha D.
Mongolischer Grosselternteil von Natascha

The source data (schemes) in the last upload from November 16th was correct (Anzahl: >1)

**Comment by fkraeutli** [comment]
Entities had both Person and Group type. Removed Person type for all entities with both types.

**Comment by fkraeutli** [comment]
fixed
