### ISSUE TITLE
Filter "Eintrag im Werkverzeichnis" not complete

### ISSUE THREAD

**Issue by MyriamSchmidt** [swiss-art-research-net/itten-app#147]
The filter option "true" shows only 50 data records. These are the 50 records from the test run in summer 2023; the complete Werkverzeichnis data was transmitted in december from Heidelberg via ZB and should contain a lot more data records! Can you please check?

**Comment by fkraeutli** [comment]
That looks correct. The Data from Heidelberg contains 331 individual Persons. However only 70 are linked to GND. We can identify the persons that appear in both our and Heidelberg data only via the GND. Out of the 70 persons with GND in Heidelberg, 50 appear in our data.

```SPARQL
PREFIX crmdig: <http://www.ics.forth.gr/isl/CRMdig/>
PREFIX : <http://www.researchspace.org/resource/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT (COUNT(?person) as ?num_persons) (COUNT(?gndEntity) as ?num_gnd) WHERE {
    ?person a <http://erlangen-crm.org/200717/E21_Person>
    FILTER(STRSTARTS(STR(?person), "http://lod.ub.uni-heidelberg.de"))
  	OPTIONAL {
    	?person owl:sameAs ?gndEntity .
    FILTER(CONTAINS(STR(?gndEntity), "gnd"))
  }
}
```

**Comment by MyriamSchmidt** [comment]
I'm not sure I understand: The number of persons with entry in the Werkverzeichnis is still only 50, because the other 20 don't appear in our JILA data?

**Comment by fkraeutli** [comment]
> I'm not sure I understand: The number of persons with entry in the Werkverzeichnis is still only 50, because the other 20 don't appear in our JILA data?

Yes exactly.

**Comment by MyriamSchmidt** [comment]
Ok thank you.
