### ISSUE TITLE
SPARQL editor page

### ISSUE THREAD

**Issue by sabweb** [swiss-art-research-net/itten-app#148]
Activating the full screen option on the SPARQL-editor window results in the JILA page header obstructing the top editor row.
![image](https://github.com/swiss-art-research-net/itten-app/assets/10222318/89fc268e-0fa8-468d-8e70-4a49052a4d13)

Also, only the SPARQL page has an additional sub navigation row ("Home / Administration / SPARQL"). Is that supposed to be visible?
![image](https://github.com/swiss-art-research-net/itten-app/assets/10222318/25cea68e-ca34-4071-a126-4b7e73d282d5)

**Comment by fkraeutli** [comment]
Thanks for noticing! We hid the button, it's an integrated functionality that doesn't work properly
