### ISSUE TITLE
Isaacs, Reginald R.: date of birth + death are missing

### ISSUE THREAD

**Issue by MyriamSchmidt** [swiss-art-research-net/itten-app#149]
https://jila.zb.uzh.ch/resource/actor:E36972CB-BAF4-387F-908D-1C54C89F1A56

The dates are present in the GND but seem to have been lost in JILA?

**Comment by fkraeutli** [comment]
Updated

**Comment by MyriamSchmidt** [comment]
The dates are still missing?

**Comment by fkraeutli** [comment]
They show up at my end. What are you seeing?

<img width="1137" alt="Screenshot 2024-03-25 at 10 15 03" src="https://github.com/swiss-art-research-net/itten-app/assets/1564625/afb5eec0-6f48-449a-8397-820c87301c70">

**Comment by MyriamSchmidt** [comment]
![Unbenannt](https://github.com/swiss-art-research-net/itten-app/assets/127132969/71137620-b733-4b22-a306-a95c4901cc79)

**Comment by MyriamSchmidt** [comment]
Now they shop up! Seems to be solved.

**Comment by MyriamSchmidt** [comment]
This issue can be closed, thanks

**Comment by thomashaensli** [comment]
thanks,
