### ISSUE TITLE
Create person overview

### ISSUE THREAD

**Issue by fkraeutli** [swiss-art-research-net/itten-app#3]
Use semantic search component to create overview of persons.
Add facets by availability:
- roles
- (num) appearances in documents
- birth year
- death year
- place of activity

![Image](https://user-images.githubusercontent.com/1564625/212095956-a687bf6a-8452-45d4-9c5b-978df1bafdec.png)

**Comment by fkraeutli** [comment]
@ChristineBaur What is the meaning of "Direkte Beziehung" vs "Indirekte Beziehung"?

**Comment by ChristineBaur** [comment]
Open to discussion. In my opinion it depends on what makes sense with the existing data and what makes sense for the user.
