### ISSUE TITLE
Create item view

### ISSUE THREAD

**Issue by fkraeutli** [swiss-art-research-net/itten-app#4]
- field visualisations
- image view

![Image](https://user-images.githubusercontent.com/1564625/212096326-d4ea904a-b72b-4701-b326-2ab75550e64b.png)

**Comment by fkraeutli** [comment]
@ChristineBaur what is the function of the icons below the image?

**Comment by ChristineBaur** [comment]
Do you mean the icons below the graph?

Here the user stories
-          Es gibt am unteren Bildschirmrand Möglichkeiten, den Graphen zu vergrössern, zu verkleinern und auf eine ganzseitige Ansicht auszurichten.
-          Es gibt am unteren Bildschirmrand Möglichkeiten, den Graphen pauschal um Knoten zu erweitern bzw. die Knotenmenge zu verringern.



</body>
</html>

**Comment by ChristineBaur** [comment]
Sorry, I didnt see the image.
- The image is downloadable as a pdf file (can maybe be included in the following icon)
- You can save the document as image file
- You can print the document.
