### ISSUE TITLE
Add details to digitised documents

### ISSUE THREAD

**Issue by fkraeutli** [swiss-art-research-net/itten-app#54]
Wenn es Digitalisate hat, bei Details hinzufügen
- Lizenz der Digitalisate anzeigen (entweder Lizenz aus e-manuscripta, besser wäre Lizenz aus CMI, da dort präziser)
- Zitiervorschlag aus e-manuscripta «Quellenangabe» anzeigen

**Comment by fkraeutli** [comment]
Wo genau sind die gewünschten Informationen (im Export und/oder e-manuscripta) @ChristineBaur

**Comment by ChristineBaur** [comment]
@fkraeutli Im json-Export unter "Lizenz" Bsp. Lizenz": { "Bezeichnung": "CC BY-NC-SA 4.0", "Link": "https://creativecommons.org/licenses/by-nc-sa/4.0/"}
In e-manuscripta kann ichs Dir nur auf dem Frontend zeigen:
![image](https://github.com/swiss-art-research-net/itten-app/assets/107859453/2c9ba16b-99c8-4c71-97a7-3b597b22b549)

**Comment by fkraeutli** [comment]
Lizenz wird jetzt angezeigt. Information in e-manuscripta wird aus Metadaten generiert

<img width="355" alt="Screenshot 2023-06-19 at 13 45 16" src="https://github.com/swiss-art-research-net/itten-app/assets/1564625/c4136e31-1f51-4b38-9ea3-c656ffdd5cbc">

**Comment by fkraeutli** [comment]
add citation widget

<img width="608" alt="Screenshot 2023-06-19 at 14 26 18" src="https://github.com/swiss-art-research-net/itten-app/assets/1564625/9dbfc0c6-87e5-4c40-b49e-ff3e739ef6d0">

**Comment by ChristineBaur** [comment]
Great! Could you change the citation structure into:
Exzerpte aus "Lehrbuch der Physiologie" von E. Abderhalden, 1940. In......

In this case, Itten is not the author, but Abderhalden

**Comment by fkraeutli** [comment]
Author information is now included
