### ISSUE TITLE
Adjust landing page design

### ISSUE THREAD

**Issue by fkraeutli** [swiss-art-research-net/itten-app#65]
- put logo in header bar
- increase size of "Entdecken Sie..."

**Comment by fkraeutli** [comment]
Putting logo in menu bar was discussed earlier and dismissed. Menu bar is static and therefore does not scroll with content. In smaller windows/screens, the menu bar would then occupy too much of the space. Therefore, the larger logo on the landing page is outside the menu bar.

We can add the logo also in the menu bar but then it is doubled and might look odd.

**Comment by MyriamSchmidt** [comment]
I would rather not double the logo. Can we move it to the right (including the "Entdecken Sie"- text) so it forms a vertical line with the white column of the menu bar?
![Schriftzug](https://github.com/swiss-art-research-net/itten-app/assets/127132969/5a4c0bf9-e750-4ad3-8958-a9e690c0ace6)
