### ISSUE TITLE
Back button should go to previous view

### ISSUE THREAD

**Issue by fkraeutli** [swiss-art-research-net/itten-app#67]
Button mit dem man zur vorhergegangenen Seite zurückkommt (aktuell geht der Retour-Knopf immer wieder auf die Startseite zurück)

**Comment by fkraeutli** [comment]
Per earlier discussion with Christine this is out of scope for the network view, as we would have to integrate a history.

**Comment by MyriamSchmidt** [comment]
@fkraeutli Could you please explain the issue with integrating a history? Is it a technical matter?

**Comment by fkraeutli** [comment]
Yes. The user can have an individual trajectory through the graph, so we would need to implement a way to record the journey of a user through the graph and then "play it backwards". This is not trivial, especially because the graph can grow quite big so the graph history can grow exponentially.
