### ISSUE TITLE
Move reset button to the left

### ISSUE THREAD

**Issue by fkraeutli** [swiss-art-research-net/itten-app#77]
Der Reset-Knopf sollte besser links (beim Graphen) erscheinen, wird sonst nicht gesehen

**Comment by fkraeutli** [comment]
Ist mit Reset-Knopf dieser gemeint?

![Image](https://github.com/swiss-art-research-net/itten-app/assets/1564625/c6cc5aa2-d587-48aa-ab4b-da938145d683)

**Comment by MyriamSchmidt** [comment]
![Reset](https://github.com/swiss-art-research-net/itten-app/assets/127132969/24f81fbb-2ede-4039-83c1-a587ca902911)
Damit ist das grüne Banner gemeint

**Comment by fkraeutli** [comment]
Ah ok

**Comment by fkraeutli** [comment]
Banner appears top left now

![Image](https://github.com/swiss-art-research-net/itten-app/assets/1564625/b908d755-7d56-4474-96ce-b2bef3499a4f)
