### ISSUE TITLE
Address issue Check Datenvisualisierung

### ISSUE THREAD

**Issue by fkraeutli** [swiss-art-research-net/itten-app#82]
Offene Umsetzungen des Issues «Check Datenvisualisierung» 
https://github.com/swiss-art-research-net/itten-zb/issues/45

**Comment by fkraeutli** [comment]
Have largely been implemented. Suggestion to revisit issues after update

**Comment by fkraeutli** [comment]
see also

https://github.com/swiss-art-research-net/itten-zb/issues/65
https://github.com/swiss-art-research-net/itten-zb/issues/67
https://github.com/swiss-art-research-net/itten-zb/issues/68

**Comment by MyriamSchmidt** [comment]
Not yet implemented (?): https://github.com/swiss-art-research-net/itten-zb/issues/45#issuecomment-1590847692
