### ISSUE TITLE
Check citations

### ISSUE THREAD

**Issue by fkraeutli** [swiss-art-research-net/itten-app#84]
Zitierweise bei den Zitiervorschlägen prüfen und korrigieren

**Comment by fkraeutli** [comment]
need more info

**Comment by MyriamSchmidt** [comment]
Current citation format (?):
[Urheber], [Entstehungsdatum]. [Titel]. In [Publikation]. [Ort]: [Institution]. Available at [URL]. Accessed [Stand]

Problem: If there is no author or date of creation, the citation is completed with author = JILA and/or date = 2023. This leads to differences in citation formats as well as irritating citations like JILA, 1912. Fotografie, Johannes Itten und Absolventen der Universität Bern mit Sekundarlehrer-Diplom abgebildet. In Johannes Itten Linked Archive. Zürich: Zentralbibliothek Zürich. Available at...

Suggestion of new citation format:
[Urheber falls bekannt]: [Titel]. [Entstehungsdatum]. In [Publikationskürzel Publikation] [Publikationsdatum = 2023]. [Ort = Zürich]: [Institution = Zentralbibliothek Zürich]. Available at [URL]. Accessed [Datum]

Example Einzelstück, Urheber unbekannt:
Fotografie, Johannes Itten und Absolventen der Universität Bern mit Sekundarlehrer-Diplom abgebildet. 1912. In JILA _Johannes Itten Linked Archive_ 2023. Zürich: Zentralbibliothek Zürich. Available at...

Example Einzelstück, Urheber bekannt:
Itten, Johannes: Johannes Itten an Alvar Aalto. 30.06.1952. In JILA _Johannes Itten Linked Archive_ 2023. Zürich: Zentralbibliothek Zürich. Available at…

Example Teilserie, Urheber unbekannt:
Lucia Moholy (1894-1989). Ca. 1920 er - 1985. In JILA _Johannes Itten Linked Archive_ 2023. Zürich: Zentralbibliothek Zürich. Available at...

Example Teildossier, Urheber bekannt:
Ardôn, Mordeḵay: Korrespondenz von Mordecai Ardon an Johannes Itten. 1946 – 1984. In JILA _Johannes Itten Linked Archive_ 2023. Zürich: Zentralbibliothek Zürich. Available at…

Example identified person:
Aalto, Alvar. In JILA _Johannes Itten Linked Archive_ 2023. Zürich: Zentralbibliothek Zürich. Available at…

Example unidentified group:
Freunde von Lucia Moholy in London. In JILA _Johannes Itten Linked Archive_ 2023. Zürich: Zentralbibliothek Zürich. Available at…

Example location:
London. In JILA _Johannes Itten Linked Archive_ 2023. Zürich: Zentralbibliothek Zürich. Available at…

Thus the citation format for people / groups / documents / document series etc.  would be aligned.

Note: The date of publication most likely has to be changed to 2024.

**Comment by fkraeutli** [comment]
Changed and deployed. Can you check?

**Comment by MyriamSchmidt** [comment]
> Changed and deployed. Can you check?

Checked. Looks good. Thanks!
