### ISSUE TITLE
Add legend for colours

### ISSUE THREAD

**Issue by fkraeutli** [swiss-art-research-net/itten-app#86]
Legende beim Graphen zur Bedeutung der Farben der Knoten hinterlegen

**Comment by MyriamSchmidt** [comment]
@fkraeutli könntest Du Joëlle und mir eine Legende fürs Testing zur Verfügung stellen? Wir stellen aktuell immer noch Inkonsistenzen fest. Danke!

**Comment by fkraeutli** [comment]
| Color | Type |
|---|---|
| ![#e44343](https://placehold.co/45x15/e44343/e44343.png) | Actor |
| ![#f9987e](https://placehold.co/45x15/f9987e/f9987e.png) | Group |
| ![#FF66B3](https://placehold.co/45x15/FF66B3/FF66B3.png) | Person |
| ![#FFD966](https://placehold.co/45x15/FFD966/FFD966.png) | Collection |
| ![#0099FF](https://placehold.co/45x15/0099FF/0099FF.png) | Event |
| ![#00CC66](https://placehold.co/45x15/00CC66/00CC66.png) | Place |

**Comment by fkraeutli** [comment]
<img width="430" alt="Screenshot 2023-12-06 at 16 35 19" src="https://github.com/swiss-art-research-net/itten-app/assets/1564625/c0fde1ae-4f1f-4a4b-bd65-7c7776f5c3a5">
Added legend
