### ISSUE TITLE
Change information displayed in i

### ISSUE THREAD

**Issue by fkraeutli** [swiss-art-research-net/itten-app#88]
Bei (i) bei einer Person werden aktuell Informationen aus PICA-Feld 678 der GND eingeblendet (Feld für biografische, historische und andere Angaben). Da die an dieser Stelle hinterlegten Informationen sehr unterschiedlich sein können (Beruf, Wirkungsort o.a.), wären andere Informationen hilfreicher: Lebensdaten + Berufe z.B.

**Comment by MyriamSchmidt** [comment]
@fkraeutli Wenn wir das genaue PICA-Feld der GND wissen, das ihr bei "i" hinterlegt, können wir die noch fehlenden Datensätze in der GND ergänzen. Gerne Info an mich, danke!

**Comment by fkraeutli** [comment]
Wir benutzend derzeit:
- gndo:biographicalOrHistoricalInformation
- gndo:professionOrOccupation
aus der RDF Repräsentation. z.B. https://d-nb.info/gnd/118710990/about/lds

**Comment by MyriamSchmidt** [comment]
@fkraeutli Wäre es möglich, bei Personen deren GND-Felder leer sind, besagte Informationen für "i" über das CMI Freitext-Schema für nicht-identifizierte Personen zur Verfügung zu stellen? (Via Schemateil "Bemerkungen").

**Comment by fkraeutli** [comment]
Added dates of birth/death for all

**Comment by JoelleFischer** [comment]
The dates are mostly visible now but the "i" hasn't been added to the persons who now have their dates of birth and death displayed.

**Comment by JoelleFischer** [comment]
**Akeret, Kurt** still has no information. He would need the gnd:associatedDate .

**Fetscherin, Hans** (http://10.51.1.212/resource/actor:FE0DB7C6-7482-3032-866A-D1C1086AD428) has nothing displayed but has a profession on GND.

**Urfer, Werner** (http://10.51.1.212/resource/actor:09983EAD-9BD5-3258-BA87-DB9DF16D3D79) has a profession as well as dates of birth and death on GND but nothing is displayed on JILA.

**Barocelli, Pietro** (http://10.51.1.212/resource/actor:BD9AD14A-1A12-333E-A29F-86E2D93C29E3) has a profession on GND but on JILA his dates of birth/death are displayed.

**Bucarelli, Palma** (http://10.51.1.212/resource/actor:72D75BD0-226A-335B-AC42-AEEC38A85C53) has a profession on GND but on JILA his dates of birth/death are displayed.

**Maas, Leonore** (http://10.51.1.212/resource/actor:D5D35116-AEA8-399E-944A-FBA854A8C0D2) has a profession on GND but on JILA her dates of birth/death are displayed.

**Marcazzan, Mario** (http://10.51.1.212/resource/actor:75200CDA-9A32-383A-9B33-6FDF77AF93F4) has a profession on GND but on JILA his dates of birth/death are displayed.

**Pfeiffer-Watenpuhl, Max** (http://10.51.1.212/resource/actor:E81CDB62-67AB-33DC-A633-334C433265D0) has a profession on GND but on JILA his dates of birth/death are displayed.

**Raehlmann, Eduard** (http://10.51.1.212/resource/actor:3A3A7A4F-C22B-35DC-8AE6-DE09E1534CA2) has a profession on GND but on JILA his dates of birth/death are displayed.

**Reidemeister, Leopold** (http://10.51.1.212/resource/actor:05BED8E0-733D-3EB3-B379-593AA1D2AE4E) has a profession on GND but on JILA his dates of birth/death are displayed.

**Rivière, Georges Henri** (http://10.51.1.212/resource/actor:505864FE-4B8D-3FF3-9A8E-F267858BE201) has a profession on GND but on JILA his dates of birth/death are displayed.

**Sansoni, Artur** (http://10.51.1.212/resource/actor:437E8947-5673-3E29-BA83-FCEB191C4824) has a profession on GND but on JILA his dates of birth/death are displayed.

**Sharma, Venkatesh Narayan** (http://10.51.1.212/resource/actor:123F3D0E-063C-3283-933E-521DA13C5F80) has a profession on GND but on JILA his dates of birth/death are displayed.

**Stauch, Carmen** (http://10.51.1.212/resource/actor:38E8CEE3-A77B-305F-8981-84BB18CD8A89) has dates of birth and death on GND, which are not displayed on JILA.

**VonErffa, Helmut** (http://10.51.1.212/resource/actor:ABEEB060-AD4A-3C02-83FF-5A32C6DA3EC6) has a profession on GND but on JILA there are the dates of birth and death displayed.

**Wettergren, Erik** (http://10.51.1.212/resource/actor:22625E9A-2BD6-304B-97E8-349D69372E0F) has a profession on GND but on JILA there are the dates of birth and death displayed.

**Comment by fkraeutli** [comment]
@JoelleFischer It seems that at least for some of the entries above the GND number has changed.
It's unfortunately not easily noticeable.

For Urfer, Werner, the link in GND is https://d-nb.info/gnd/1090147546. But when I click on it, I get redirected to https://d-nb.info/gnd/129383821.

Would you mind checking the above entries if the missing information might be due to changed GND number? If so, it would make sense to fix this in the source data.

**Comment by JoelleFischer** [comment]
Thanks for the hint. "Urfer, Werner", "Raelmann, Eduard" and "Rivière, Georges Henri" all had the same problem. I fixed it in our registry in CMI.

The others were ok though.

**Comment by fkraeutli** [comment]
Thanks, I'll check the remaining ones

**Comment by fkraeutli** [comment]
Barocelli, Pietro seems to have profession not as entity but as literal using `https://d-nb.info/standards/elementset/gnd#professionOrOccupationAsLiteral`. Will add

**Comment by fkraeutli** [comment]
Same with: 
- Bucarelli, Palma
- Maas, Leonore
- Marcazzan, Mario
- Pfeiffer-Watenpuhl, Max
- Raehlmann, Eduard 
- Reidemeister, Leopold
- Sansoni, Artur
- Sharma, Venkatesh Narayan
- VonErffa, Helmut
- Wettergren, Erik

Different issue:
- Stauch, Carmen

**Comment by fkraeutli** [comment]
Stauch, Carmen as birth and death date combined in `gndo:dateOfBirthAndDeath`

**Comment by fkraeutli** [comment]
The information in "i" should now appear. I also added it to the details panel.

**Comment by JoelleFischer** [comment]
Thank you. Now all of those with the unchanged GND-Numbers have their "i"s.

Some issues persist though:

- As to the english version of JILA: there still is no equivalent to "Wirkungsdatum" (Associated date) visible.
- Pfeiffer-Watenphul Max still has no Date of Death added on JILA.
- Isaacs, Reginald R. displays no occupation in "i" or in the details panel.

**Comment by fkraeutli** [comment]
<img width="234" alt="Screenshot 2023-12-19 at 14 28 54" src="https://github.com/swiss-art-research-net/itten-app/assets/1564625/68fdcee0-863b-4e97-9820-6ee4e85b10f8">

Associated date is visible at my and. Maybe a cache issue?

**Comment by fkraeutli** [comment]
Re-retreiving GND data to check for missing values

**Comment by JoelleFischer** [comment]
The translation of the associated date is now visible.
